# Generated by Django 4.2.1 on 2023-09-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Info',
            fields=[
                ('ts_id', models.BigIntegerField(max_length=10, primary_key=True, serialize=False)),
                ('deposit_amount', models.BigIntegerField(max_length=10)),
                ('balance_amount', models.BigIntegerField(max_length=10)),
                ('withdraw_amount', models.BigIntegerField(max_length=10)),
                ('ts_dt', models.DateTimeField(auto_now_add=True)),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.cust_info')),
            ],
        ),
    ]
