# Generated by Django 4.2.1 on 2023-09-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0003_account_info_ts_st_alter_account_info_balance_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30)),
                ('cust_email', models.EmailField(max_length=50)),
                ('cust_city', models.CharField(max_length=15)),
                ('cust_mobile', models.BigIntegerField(max_length=10)),
                ('loan_amount', models.BigIntegerField(default=0)),
            ],
        ),
    ]
